### ISSUE TITLE
packege jQuery-Mask-Plugin not work in meteor

### ISSUE THREAD

**Issue by Hana9** [igorescobar/jQuery-Mask-Plugin#528]
I instaled the package
`meteor add igorescobar:jquery-mask-plugin`
and when that i run app
app is fail with this error
```
/home/xxxx/.meteor/packages/meteor-tool/.1.4.2_3.axfajw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
 						throw(ex);
 						^
 
ReferenceError: window is not defined
at meteorInstall.node_modules.meteor.igorescobar:jquery-mask-plugin.dist.jquery.mask.js (packages/igorescobar:jquery-mask-plugin/dist/jquery.mask.js:540:4)
at fileEvaluate (packages/modules-runtime.js:181:9)
at require (packages/modules-runtime.js:106:16)
at /home/xxxx/app/.meteor/local/build/programs/server/packages/igorescobar_jquery-mask-plugin.js:657:1
at /home/xxxx/app/.meteor/local/build/programs/server/packages/igorescobar_jquery-mask-plugin.js:664:3
at /home/xxxx/app/.meteor/local/build/programs/server/boot.js:295:34
at Array.forEach (native)
at Function._.each._.forEach (/home/xxxx/app/.meteor/packages/meteor-tool/.1.4.2_3.axfajw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
at /home/xxxx/app/.meteor/local/build/programs/server/boot.js:128:5
at /home/xxxx/app/.meteor/local/build/programs/server/boot.js:344:5
```

**Comment by cvgustavo** [comment]
Up! Same problem here.

**Comment by lindoelio** [comment]
+1

**Comment by igorescobar** [comment]
`window` is kinda required for this to work. I'm not sure how to fix this :)

**Comment by igorescobar** [comment]
Guys I won't let this open without activity ok?
Let me know if you want to work on this with me.

**Comment by jkutianski** [comment]
@igorescobar Package is misspelled on the title (packege)
